// <auto-generated />
using System;
using Kokoon.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Kokoon.Core.Persistence.Migrations;

[DbContext(typeof(KokoonDbContext))]
partial class KokoonDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("Kokoon.Core.Persistence.DownloadItemEntity", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("CompletedAt")
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<long>("DownloadedBytes")
                .HasColumnType("INTEGER");

            b.Property<long?>("DurationTicks")
                .HasColumnType("INTEGER");

            b.Property<string>("FileName")
                .IsRequired()
                .HasMaxLength(260)
                .HasColumnType("TEXT");

            b.Property<string>("FormatId")
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("MimeType")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("Mode")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT")
                .HasDefaultValue("Http");

            b.Property<string>("Referer")
                .HasMaxLength(2048)
                .HasColumnType("TEXT");

            b.Property<string>("SavePath")
                .IsRequired()
                .HasMaxLength(1024)
                .HasColumnType("TEXT");

            b.Property<int>("SegmentCount")
                .HasColumnType("INTEGER");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("TEXT");

            b.Property<bool>("SupportsRanges")
                .HasColumnType("INTEGER");

            b.Property<string>("ThumbnailUrl")
                .HasMaxLength(2048)
                .HasColumnType("TEXT");

            b.Property<long>("TotalBytes")
                .HasColumnType("INTEGER");

            b.Property<string>("Url")
                .IsRequired()
                .HasMaxLength(2048)
                .HasColumnType("TEXT");

            b.Property<string>("VideoTitle")
                .HasMaxLength(500)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("CreatedAt")
                .HasDatabaseName("IX_DownloadItems_CreatedAt");

            b.HasIndex("Status")
                .HasDatabaseName("IX_DownloadItems_Status");

            b.ToTable("DownloadItems");

            b.OwnsMany("Kokoon.Core.Persistence.SegmentEntity", "Segments", b1 =>
            {
                b1.Property<int>("Index")
                    .HasColumnType("INTEGER");

                b1.Property<long>("BytesDownloaded")
                    .HasColumnType("INTEGER");

                b1.Property<long>("EndByte")
                    .HasColumnType("INTEGER");

                b1.Property<long>("StartByte")
                    .HasColumnType("INTEGER");

                b1.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b1.Property<string>("TempFilePath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b1.ToJson();
            });
        });
#pragma warning restore 612, 618
    }
}
